"""
    File: TestSequenceUtils
    Author: steve
    Created: 09/08/2014
    
"""
import unittest
import timeit
import SequenceUtils
import cProfile, pstats, StringIO

class TestSequenceFunctions(unittest.TestCase):

    def test_seq_to_int_with_empty_seq(self):
        result = SequenceUtils.sequence_to_int("")
        self.assertEqual(result, 0)


    def test_seq_to_int_all_a(self):
        result = SequenceUtils.sequence_to_int("AAAA")
        self.assertEqual(result, 0)

    def test_seq_to_int_all_c(self):
        result = SequenceUtils.sequence_to_int("CCCC")
        # expect result to be 1+4+16+64
        self.assertEqual(result, 85)


    def test_seq_to_int_all_g(self):
        result = SequenceUtils.sequence_to_int("GGGG")
        # expect result to be 2 * 1+4+16+64
        self.assertEqual(result, 170)


    def test_seq_to_int_all_t(self):
        result = SequenceUtils.sequence_to_int("TTTT")
        # expect result to be 3 * 1+4+16+64
        self.assertEqual(result, 255)


    def test_seq_to_int_one_of_each(self):
        result = SequenceUtils.sequence_to_int("ACGT")
        # expect result to be 0*64 + 1*16 +  2*4 + 3
        self.assertEqual(result, 27)


    def test_seq_to_int_one_of_each_reversed(self):
        result = SequenceUtils.sequence_to_int("TGCA")
        # expect result to be 3*64 + 2*16 + 1*4 + 0
        self.assertEqual(result, 228)


    def test_seq_to_int_longer(self):
        result = SequenceUtils.sequence_to_int("CGTATTGATTCCCGATAGT")
        self.assertEqual(result, 117008324811)

    def test_seq_to_int_error(self):
        self.assertRaises(ValueError, SequenceUtils.sequence_to_int, "ACGTBCGTA")


    def test_int_to_seq_with_zero_number(self):
        result = SequenceUtils.int_to_sequence(0,0)
        self.assertEqual(result, "")


    def test_int_to_seq_all_a(self):
        result = SequenceUtils.int_to_sequence(0, 4)
        self.assertEqual(result, "AAAA")

    def test_int_to_seq_all_c(self):
        result = SequenceUtils.int_to_sequence(85, 4)
        # expect result to be 1+4+16+64
        self.assertEqual(result, "CCCC")


    def test_int_to_seq_all_g(self):
        result = SequenceUtils.int_to_sequence(170, 4)
        # expect result to be 2 * 1+4+16+64
        self.assertEqual(result, "GGGG")


    def test_int_to_seq_all_t(self):
        result = SequenceUtils.int_to_sequence(255, 4)
        # expect result to be 3 * 1+4+16+64
        self.assertEqual(result, "TTTT")


    def test_int_to_seq_one_of_each(self):
        result = SequenceUtils.int_to_sequence(27, 4)
        # expect result to be 0*64 + 1*16 +  2*4 + 3
        self.assertEqual(result, "ACGT")


    def test_int_to_seq_one_of_each_reversed(self):
        result = SequenceUtils.int_to_sequence(228, 4)
        # expect result to be 3*64 + 2*16 + 1*4 + 0
        self.assertEqual(result, "TGCA")


    def test_int_to_seq_longer(self):
        result = SequenceUtils.int_to_sequence(117008324811, 19)
        self.assertEqual(result, "CGTATTGATTCCCGATAGT")


    def test_compute_kmers_simple_1(self):
        result = SequenceUtils.compute_kmers_slowly("AAAA", 2)
        self.assertEqual(len(result), 1)
        self.assertEqual(result[0], 3)


    def test_compute_kmers_simple_2(self):
        result = SequenceUtils.compute_kmers_slowly("AACC", 2)
        self.assertEqual(len(result), 3)
        self.assertEqual(result[0], 1)
        self.assertEqual(result[1], 1)
        self.assertEqual(result[5], 1)


    def test_compute_kmers_fast(self):
        seq = "CGTATTGATTCCATTATTATTCATTAGATTAAGT"
        kmers_1 = SequenceUtils.compute_kmers_slowly(seq, 4)
        kmers_2 = SequenceUtils.compute_kmers_fast(seq, 4)

        self.assertEqual(kmers_1, kmers_2)


    def test_compute_kmers_fast_2(self):
        seq = "CGTATTGATTCCATTTTTTTTCCCCCGGAGAGGAGAGTCTGCTCGTATCGTCGTTATATTATGCCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTTTTTTTCCCCCGGAGAGGAGAGTCTGCTCGTATCGTCGTTATATTATGCCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTTTTTTTCCCCCGGAGAGGAGAGTCTGCTCGTATCGTCGTTATATTATGCCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTTTTTTTCCCCCGGAGAGGAGAGTCTGCTCGTATCGTCGTTATATTATGCCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTTTTTTTCCCCCGGAGAGGAGAGTCTGCTCGTATCGTCGTTATATTATGCCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTTTTTTTCCCCCGGAGAGGAGAGTCTGCTCGTATCGTCGTTATATTATGCCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTTTTTTTCCCCCGGAGAGGAGAGTCTGCTCGTATCGTCGTTATATTATGCCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTTTTTTTCCCCCGGAGAGGAGAGTCTGCTCGTATCGTCGTTATATTATGCCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTTTTTTTCCCCCGGAGAGGAGAGTCTGCTCGTATCGTCGTTATATTATGCCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTTTTTTTCCCCCGGAGAGGAGAGTCTGCTCGTATCGTCGTTATATTATGCCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTTTTTTTCCCCCGGAGAGGAGAGTCTGCTCGTATCGTCGTTATATTATGCCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTTTTTTTCCCCCGGAGAGGAGAGTCTGCTCGTATCGTCGTTATATTATGCCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTTTTTTTCCCCCGGAGAGGAGAGTCTGCTCGTATCGTCGTTATATTATGCCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTTTTTTTCCCCCGGAGAGGAGAGTCTGCTCGTATCGTCGTTATATTATGCCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTTTTTTTCCCCCGGAGAGGAGAGTCTGCTCGTATCGTCGTTATATTATGCCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTTTTTTTCCCCCGGAGAGGAGAGTCTGCTCGTATCGTCGTTATATTATGCCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTTTTTTTCCCCCGGAGAGGAGAGTCTGCTCGTATCGTCGTTATATTATGCCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTTTTTTTCCCCCGGAGAGGAGAGTCTGCTCGTATCGTCGTTATATTATGCCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTTTTTTTCCCCCGGAGAGGAGAGTCTGCTCGTATCGTCGTTATATTATGCCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTTTTTTTCCCCCGGAGAGGAGAGTCTGCTCGTATCGTCGTTATATTATGCCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTTTTTTTCCCCCGGAGAGGAGAGTCTGCTCGTATCGTCGTTATATTATGCCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTTTTTTTCCCCCGGAGAGGAGAGTCTGCTCGTATCGTCGTTATATTATGCCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTTTTTTTCCCCCGGAGAGGAGAGTCTGCTCGTATCGTCGTTATATTATGCCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTTTTTTTCCCCCGGAGAGGAGAGTCTGCTCGTATCGTCGTTATATTATGCCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTTTTTTTCCCCCGGAGAGGAGAGTCTGCTCGTATCGTCGTTATATTATGCCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTTTTTTTCCCCCGGAGAGGAGAGTCTGCTCGTATCGTCGTTATATTATGCCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTTTTTTTCCCCCGGAGAGGAGAGTCTGCTCGTATCGTCGTTATATTATGCCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTTTTTTTCCCCCGGAGAGGAGAGTCTGCTCGTATCGTCGTTATATTATGCCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGTCGTATTGATTCCATTATTATTCATTAGATTAAGT"


        pr = cProfile.Profile()
        pr.enable()
        # ... do something ...
        kmers_1 = SequenceUtils.compute_kmers_slowly(seq, 40)

        kmers_2 = SequenceUtils.compute_kmers_fast(seq, 40)

        self.assertEqual(kmers_1, kmers_2)

        pr.disable()
        s = StringIO.StringIO()
        sortby = 'cumulative'
        ps = pstats.Stats(pr, stream=s).sort_stats(sortby)
        ps.print_stats()
        print s.getvalue()



if __name__ == '__main__':
    unittest.main()